#!/usr/bin/env python3
"""WP12 -- generate the manuscript's LaTeX tables.

Appendix A of the manuscript was an empty heading, which means WP10's own
external-reader gate was never met: a reader could not see which branch carries
which number, nor which branches rest on mass-function cells that failed their
gate.  This script generates that table, and the smaller in-text ones, directly
from the versioned artifacts.  Nothing here is typed.

The full 54-branch table is too wide for an A&A column, so it is produced twice:
a compact printed version keyed on the quantities the text actually discusses,
and a complete machine-readable CSV for electronic publication.

Outputs:
  manuscript/tables_generated.tex     \\input by main.tex
  tables/wp12_appendix_a_full.csv     the electronic version
  provenance/wp12_tables_execution.json

Run:
  PYTHONPATH=scripts python3 scripts/wp12_tables.py
"""
from __future__ import annotations

import json

import numpy as np
import pandas as pd

import chain as C
import wp5_common as w
import wp12_common as W

MANUSCRIPT = w.ROOT / "manuscript"
OUT = MANUSCRIPT / "tables_generated.tex"


def tick(flag: bool) -> str:
    return r"$\checkmark$" if flag else r"$\times$"


def fam(name: str) -> str:
    return "PA" if name == "PARSEC" else "MI"


def header(title: str) -> str:
    return (
        "% -----------------------------------------------------------------\n"
        f"% {title}\n"
        "% GENERATED by scripts/wp12_tables.py -- do not edit by hand.\n"
    )


# ---------------------------------------------------------------- Appendix A
def appendix_a(table: pd.DataFrame) -> str:
    lines = [
        header("Table A.1 -- branch and fit-quality table"),
        r"\begin{table*}",
        r"\caption{The \NSNallbranches\ all-explode branches, their "
        r"mass-function fit-quality status and their results.  Family PA = PARSEC, "
        r"MI = MIST.  $\delta$ is the star-formation duration in Myr.  "
        r"Columns A, B, C give the residual-fit verdict for each subgroup "
        r"at that family, $R_V$ and $\alpha$; \emph{all} is their conjunction. "
        r"$\Sigma$ is the star-weighted association closure ratio.  $S$ is the "
        r"conditional scenario-availability score of "
        r"Sect.~\ref{sec:cocoon}, \emph{not} a calibrated probability.  "
        r"Branches with $\alpha = 2.6$ are sensitivity cases outside the "
        r"headline set.  The complete table, including per-subgroup closure "
        r"ratios, black-hole-threshold columns and Poisson intervals, is "
        r"available electronically.}",
        r"\label{tab:branches}",
        r"\centering",
        r"\small",
        r"\begin{tabular}{llrrr ccc c rrrr r}",
        r"\hline\hline",
        r"& fam. & $R_V$ & $\alpha$ & $\delta$ & A & B & C & all & "
        r"$\Sigma$ & $N_{\rm SN}$ & 68\% & $P_{100}$ & $S$ \\",
        r"\hline",
    ]
    for i, row in enumerate(table.itertuples(), start=1):
        mark = r"$\star$" if "BASELINE" in row.notes else ""
        lines.append(
            f"{mark} & {fam(row.family)} & {row.R_V:g} & {row.alpha:g} & "
            f"{row.sf_duration_Myr:g} & "
            f"{tick(row.wp5_gate_A)} & {tick(row.wp5_gate_B)} & "
            f"{tick(row.wp5_gate_C)} & {tick(row.all_subgroup_pass)} & "
            f"{row.closure_association:.2f} & {row.N_SN_mean:.2f} & "
            f"[{row.N_SN_p16:.0f}, {row.N_SN_p84:.0f}] & "
            f"{row.P_last_SN_within_100kyr:.2f} & "
            f"{row.scenario_score:.3f} \\\\"
        )
        if i % 18 == 0 and i < len(table):
            lines.append(r"\hline")
    lines += [
        r"\hline",
        r"\end{tabular}",
        r"\tablefoot{$\star$ marks the baseline branch.  A $\times$ in "
        r"columns A--C marks a subgroup whose mass-function fit failed the "
        r"residual-fit criterion at that family, $R_V$ and $\alpha$; such branches are "
        r"retained as explicit sensitivity cases and are never deleted, but "
        r"they are not validated fits.}",
        r"\end{table*}",
        "",
    ]
    return "\n".join(lines)


# ------------------------------------------------------- in-text small tables
def gate_summary() -> str:
    landscape = json.loads(
        (C.tag(w.PROVENANCE / "wp12_gate_landscape_execution.json")).read_text())
    closure = json.loads(
        (C.tag(w.PROVENANCE / "wp12_closure_slopes_execution.json")).read_text())
    scenario = json.loads(
        (C.tag(w.PROVENANCE / "wp12_scenario_score_execution.json")).read_text())
    neighbour = json.loads(
        (C.tag(w.PROVENANCE / "wp12_neighbour_budget_execution.json")).read_text())
    ledger_exec = json.loads(
        (C.tag(w.PROVENANCE / "wp7_ledger_execution.json")).read_text())
    g7a = ledger_exec.get("gate", {})

    rows = [
        ("Prior-art and scope review", r"\textsc{pass}",
         "no direct duplicate; one partial overlap cited"),
        ("Data acquisition and marker freeze", r"\textsc{pass}",
         "catalogues recorded; external markers fixed before the ledger"),
        ("Membership and kinematic structure", r"\textsc{pass}",
         "all eight acceptance criteria met after one rejected trial"),
        ("Per-star extinction mapping", r"\textsc{pass}",
         "accepted after repairing the sparse-anchor treatment"),
        ("Ages and stellar masses", r"\textsc{partial}",
         "Cyg~OB2-B's age and supernova contribution remain one-sided"),
        ("IMF normalization", r"\textsc{partial}",
         f"baseline passes in all three subgroups; "
         f"{landscape['repair_v7_breakdown']['cells_passing']} of "
         f"{landscape['repair_v7_breakdown']['cells_total']} cells pass"),
        ("Massive-star closure and runaways", r"\textsc{pass}",
         "both validation criteria met; three earlier defects withdrawn"),
        ("Supernova ledger", r"\textsc{partial}",
         "three of four validation criteria met; relative convergence failed"),
        ("Independent supernova cross-checks", r"\textsc{pass}",
         "four criteria and five pre-registered predictions met"),
        ("Pre-registered framing rule", r"\textsc{pass}",
         r"rule returned \textsc{inconclusive} mechanically"),
        ("Radioactive-isotope forecast", r"\textsc{partial}",
         "post-hoc; one test was vacuous and its corrected form failed"),
        ("Fit-landscape and scenario sensitivities", r"\textsc{partial}",
         "neighbouring-population calibration failed and scoped that claim out"),
        ("Manuscript and reproducibility", r"\textsc{pass}",
         "generated numbers, source validation and clean PDF build pass"),
    ]
    lines = [
        header("Table 2 -- validation summary"),
        r"\begin{table*}",
        r"\caption{Validation status for each scientific analysis stage and the "
        r"consequence carried downstream.  \textsc{partial} means the stage was "
        r"usable while a named criterion or limitation remained; the failure "
        r"is reported in the "
        r"text and was not reinterpreted.}",
        r"\label{tab:validation}",
        r"\centering",
        r"\small",
        r"\begin{tabular}{lll}",
        r"\hline\hline",
        r"analysis stage & verdict & consequence \\",
        r"\hline",
    ]
    for stage, verdict, consequence in rows:
        lines.append(
            f"{stage} & {verdict} & "
            f"\\parbox[t]{{0.48\\textwidth}}{{\\raggedright {consequence}}} \\\\"
        )
    lines += [
        r"\hline",
        r"\end{tabular}",
        r"\end{table*}",
        "",
    ]
    _ = (closure, scenario, neighbour, g7a)
    return "\n".join(lines)


def cocoon_terms() -> str:
    scenario = json.loads(
        (C.tag(w.PROVENANCE / "wp12_scenario_score_execution.json")).read_text())
    c4 = scenario["wp12_3_c4_sensitivity"]
    c3 = scenario["wp12_4_c3_subtype"]
    lines = [
        header("Table 3 -- the conditional cocoon terms"),
        r"\begin{table*}",
        r"\caption{The three factors of the conditional scenario-availability "
        r"score $S = C_1 C_3 C_4$, with what each one actually is.  Only $C_1$ "
        r"is a sampled probability.  The product is therefore a scenario "
        r"score, not a calibrated probability, and the paper does not present "
        r"it as one.}",
        r"\label{tab:cocoon}",
        r"\centering",
        r"\small",
        r"\begin{tabular}{@{}p{0.05\textwidth}p{0.17\textwidth}"
        r"p{0.28\textwidth}p{0.34\textwidth}@{}}",
        r"\hline\hline",
        r"term & what it is & numerical treatment & dominant limitation \\",
        r"\hline",
        r"$C_1$ & sampled Monte-Carlo probability & "
        r"$P(\ge 1$ explosion in the required age window$)$, per branch & "
        r"\raggedright inherits the age and IMF branch structure; spans a "
        r"factor of two across the headline set \tabularnewline",
        r"$C_3$ & deterministic model mapping & "
        r"indicator that the progenitor exceeded $30\,M_\odot$ & "
        r"\raggedright returns exactly unity "
        r"because the ledger's mass floor lies above the threshold; falls to "
        + f"{c3['pessimistic_60_Msun_C3_range'][0]:.2f}" +
        r" under a $60\,M_\odot$ assumption \tabularnewline",
        r"$C_4$ & upper bound & "
        r"held fixed at " + f"{c4['adopted_C4']:.3f}" + r" & "
        r"\raggedright a two-dimensional, "
        r"footprint-limited runaway census of \emph{living} stars below the "
        r"turnoff, applied to dead and more massive progenitors \tabularnewline",
        r"\hline",
        r"\end{tabular}",
        r"\end{table*}",
        "",
    ]
    return "\n".join(lines)


def subgroup_summary() -> str:
    gate = W.gate_map()
    base = gate[
        gate.family.eq(W.BASE["family"]) & gate.R_V.eq(W.BASE["R_V"])
        & gate.alpha.eq(W.BASE["alpha"])
    ].set_index("subgroup")
    closure_exec = json.loads(
        (C.tag(w.PROVENANCE / "wp12_closure_slopes_execution.json")).read_text())
    grid = closure_exec["subgroup_grid_median_closure_by_alpha"]
    slopes = pd.read_csv(C.tag(w.TABLES / "wp12_closing_slopes.csv"))
    labels = pd.read_parquet(W.frozen("wp2_subgroup_labels"))
    extinction = pd.read_parquet(W.frozen("wp3_extinction"))
    # The extinction catalogue carries one A_V column per carried extinction
    # law; the baseline branch is R_V = 3.1.
    av_col = f"av_rv{W.BASE['R_V']:g}"
    if av_col not in extinction.columns:
        raise KeyError(
            f"{av_col} not in the WP3 extinction catalogue; columns are "
            f"{[c for c in extinction.columns if c.startswith('av_')]}"
        )
    members = labels.merge(
        extinction[["source_id", av_col]], on="source_id", how="left"
    )
    ledger = W.ledger()
    subs = ledger[
        ledger.scope.eq("subgroup") & ledger.explodability.eq("all_explode")
        & ledger.family.eq(W.BASE["family"]) & ledger.R_V.eq(W.BASE["R_V"])
        & ledger.alpha.eq(W.BASE["alpha"])
        & ledger.sf_duration_Myr.eq(W.BASE["sf_duration_Myr"])
    ].set_index("subgroup")

    lines = [
        header("Table 1 -- subgroup summary"),
        r"\begin{table*}",
        r"\caption{The three kinematic subgroups on the baseline branch "
        r"(PARSEC, $R_V = 3.1$, $\alpha = 2.3$, $\delta = 0$).  The age is the "
        r"counts-based age the ledger consumes, not the colour--magnitude "
        r"prior.  Closure is the grid median over the six family--$R_V$ cells "
        r"at $\alpha = 2.3$, and the closing slope is the slope at which that "
        r"subgroup's census would close exactly.  A $\times$ in the fit-status "
        r"column marks a subgroup whose baseline mass-function fit failed the "
        r"residual-fit criterion; none does.}",
        r"\label{tab:subgroups}",
        r"\centering",
        r"\small",
        r"\begin{tabular}{lrrrrrrrc}",
        r"\hline\hline",
        r"subgroup & $N$ & median $A_V$ & age & $k$ & closure & closing "
        r"$\alpha$ & $N_{\rm SN}$ & fit \\",
        r" & & (mag) & (Myr) & & at $\alpha=2.3$ & & & \\",
        r"\hline",
    ]
    for subgroup in w.SUBGROUPS:
        tag = subgroup[-1]
        row = base.loc[subgroup]
        n = int(labels.subgroup.eq(subgroup).sum())
        av = (
            float(members[members.subgroup.eq(subgroup)][av_col].median())
            if av_col else float("nan")
        )
        closing = float(
            slopes[slopes.subgroup.eq(subgroup)].closing_alpha_interpolated.median()
        )
        lines.append(
            f"Cyg~OB2-{tag} & {n:d} & "
            + (f"{av:.2f}" if np.isfinite(av) else "--")
            + f" & {row.truth_age_posterior_mean_Myr:.2f} & "
            f"{row.k_median:,.0f} & {grid[subgroup]['alpha_2.3']:.2f} & "
            f"{closing:.2f} & {subs.loc[subgroup].N_SN_mean:.2f} & "
            f"{tick(bool(row.residual_gate_pass))} \\\\"
        )
    lines += [
        r"\hline",
        r"\end{tabular}",
        r"\end{table*}",
        "",
    ]
    return "\n".join(lines)


def main() -> None:
    table = pd.read_csv(C.tag(w.TABLES / "wp12_branch_gate_table.csv"))
    table = table.sort_values(
        ["alpha", "family", "R_V", "sf_duration_Myr"]
    ).reset_index(drop=True)

    full = table.copy()
    full.to_csv(C.tag(w.TABLES / "wp12_appendix_a_full.csv"), index=False)

    body = "\n".join([
        "% =================================================================",
        "% manuscript/tables_generated.tex -- GENERATED, DO NOT EDIT BY HAND.",
        "% Produced by scripts/wp12_tables.py from versioned artifacts.",
        "% Regenerate with:",
        "%   PYTHONPATH=scripts python3 scripts/wp12_tables.py",
        "% =================================================================",
        "",
        subgroup_summary(),
        gate_summary(),
        cocoon_terms(),
        appendix_a(table),
    ])
    OUT.write_text(body)

    rec = W.record(
        "scripts/wp12_tables.py",
        {
            "item": "WP12 -- generated LaTeX tables",
            "tables": [
                "Table 1 subgroup summary", "Table 2 gate summary",
                "Table 3 conditional cocoon terms",
                "Table A.1 branch and gate table",
            ],
            "appendix_a_rows": int(len(table)),
            "appendix_a_electronic": "tables/wp12_appendix_a_full.csv",
        },
        {"tex": OUT, "csv": C.tag(w.TABLES / "wp12_appendix_a_full.csv")},
    )
    w.write_json(C.tag(w.PROVENANCE / "wp12_tables_execution.json"), rec)
    print(f"wrote manuscript/tables_generated.tex ({len(table)} branch rows)")
    print(f"wrote {C.tag_rel('tables/wp12_appendix_a_full.csv')}")


if __name__ == "__main__":
    main()
